name: Release image
on:
  push:
    branches:
      - main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  deploy:

    name: Build and push to GCR
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME_ROOT: eu.gcr.io/${{ secrets.GCP_PROJECT_ID }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Build jar
        run: ./gradlew build

      - name: Authenticate in GCP
        uses: google-github-actions/setup-gcloud@v0.6.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_email: ${{ secrets.GCP_EMAIL }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configure Docker auth
        run: gcloud auth configure-docker --quiet

      - name: Setting environment variables
        run: |
          echo "image_name=${IMAGE_NAME_ROOT}/$(./gradlew -q getImageName)" >> $GITHUB_ENV
          echo "artifact_name=$(./gradlew -q getArtifactName)" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          cp build/libs/*.jar "docker/${{env.artifact_name}}.jar" || exit 1
          docker build docker -t ${{ env.image_name }}

      - name: Push Docker image
        run: docker push ${{ env.image_name }}

